spring:
  application:
    name: configserver
  profiles:
    active: git, zookeeper
  cloud:
    config:
      server:
        health: false
        zookeeper:
          order: 1
          connectionString: localhost
        git:
          uri: # Repo URI
          order: 2
        prefix: "springconfig"
endpoints:
  enabled: true
  actuator:
    enabled: true